config/routes.rb
Rails.application.routes.draw do
  
  root to: 'maps#current'  #Principal page
  
  resources :movements, only: [:create] #Mueve una miniatura

  resources :characters, except: [:show]
  resources :character_views, only: [:create] #Es el js que se hace con js para la vista del mapa

  resources :maps, only: [:new, :edit, :create, :index] #Solo para el master
  resources :map_visibilities, only: [:create, :destroy] #Solo para el master

  resources :tiles, only: [:update] #Solo para el master
  post 'edit_tile', to: 'tiles#edit_tile'

  resources :attacks, only: [:create, :destroy]
  resources :armors, only: [:create, :destroy]
  resources :known_spells, only: [:create, :destroy]
  resources :prepared_spells, only: [:create, :destroy]


  get 'login', to: 'basic_pages#login'
  post 'login', to: 'basic_pages#register'  
  get 'logout', to: 'basic_pages#logout'
end

app/models/map.rb
# == Schema Information
#
# Table name: maps
#
#  id                    :bigint           not null, primary key
#  map_type              :string
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  background_image_link :string
#  is_current            :boolean
#  name                  :string
#

class Map < ApplicationRecord
  has_many :rows

  def self.generate(height: 15, width: 15, map_type: 'castle', background_image_link: '', name: '')
    map = self.create(map_type: map_type, background_image_link: background_image_link, name: name)
    height.to_i.times do |ordinate|
      Row.generate(width: width.to_i, ordinate: ordinate, map_id: map.id)
    end
    return map
  end

  def self.current
    @map = Map.where(is_current: true).last || Map.last
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController  
  before_action :check_for_master, except: [:current]

  def current
    @map = Map.current
    @characters = Character.owner_is(cookies[:user])
    #El último es solo para casos extremos; debo verificar que toda persona logueada tenga un personaje
    @character = @characters.find_by(id: cookies[:character_id]) || @characters.first || Character.new 
    @map_characters = Character.in_map
  end

  def new
    @map = Map.new
    #Simplemente preguntará por el tipo de mapa y el tamaño y por defecto se creará con simples
    #Existirá el edit del mapa y el update de los tiles.
  end

  def create
    @map = Map.generate(map_params.to_h.symbolize_keys)
    if @map.save
      redirect_to edit_map_path(@map)
    else
      redirect_to root_path
    end
  end

  def edit
    @map = Map.find(params[:id])    
  end

  #No hay update sino que lo que se updatea son los tiles

  def index
    @maps = Map.all.order(:is_current, id: :desc)
  end

  private

    def check_for_master
      unless cookies[:user] == "Mmaster"
        redirect_to root_path
      end
    end

    def map_params
      params.require(:map).permit(:height, :width, :map_type, :background_image_link, :name)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_character.html.slim
p.is-size-3
  = "#{character.name} #{character.icon}"
p = "Max HP: #{character.hp_max}"
p = "AC: #{character.calculate_ac}"
p.is-size-4.has-text-danger Ataques
- character.attacks.each do |attack|
  p = "#{attack.weapon} + #{attack.attack_bonus} / #{attack.damage_dice}"
p.is-size-4.has-text-danger Características
p = "Fue #{character.strength} Dex #{character.dexterity} Con #{character.constitution} Int #{character.inteligence} Car #{character.charisma} Sab #{character.wisdom}"
p.is-size-4.has-text-danger Hechizos preparados
table.table.is-narrow       
  thead
    tr
      th Nivel
      th Nombre
      th V S M F DF XP 
      th    
  tbody
    - character.prepared_spells.sort_by{|s| s.known_spell.level}.each do |prepared_spell|
      tr
        - spell = prepared_spell.known_spell
        td = spell.level
        td = spell.name
        td = spell.components
        td = link_to "close", prepared_spell_path(prepared_spell), method: :delete, class: "material-icons", style: "font-size: 1rem; font-weight: bold;"
p.is-size-4.has-text-danger Objetos
p.is-size-4.has-text-danger Notas

app/views/maps/_miniatures.html.slim
- map_characters.each do |character|
  p.miniature.character_medium style="left: #{2.37 * character.abscissa}rem; top: #{2.37 * character.ordinate}rem"
    = "#{character.icon}"

app/views/maps/current.html.slim
.map_container
  img.is_background src="#{@map.background_image_link}"
  .grid_container
    - @map.rows.order(:ordinate).each do |row|
      .row_container        
        - row.tiles.order(:abscissa).each do |tile|
          /button class = "grid_button #{@map.map_type}_#{tile.tile_type}"
          = button_to '', movements_path(ordinate: tile.ordinate, abscissa: tile.abscissa), class: "grid_button #{@map.map_type}_#{tile.tile_type} #{tile.tile_type}", remote: true
    - n = 33.18
    #miniatures
      = render 'miniatures', map_characters: @map_characters

    - ancho = 40
    .character_card style="left: #{ancho}rem"
      .field.is-grouped
        - Character.owner_is(cookies[:user]).in_map.each do |monster|
          .control
            = link_to "#{monster.icon} #{monster.name}", character_views_path(character_id: monster.id), remote: true, method: :post, class: "button is-warning"
      #char_container
        = render 'character', character: @character

app/views/maps/edit.html.slim
.map_container
  img.is_background src="#{@map.background_image_link}"
  .grid_container
    - @map.rows.order(:ordinate).each do |row|
      .row_container        
        - row.tiles.order(:abscissa).each do |tile|
          p[id = "tile-#{tile.ordinate}-#{tile.abscissa}", class = "grid_button #{@map.map_type}_#{tile.tile_type} #{tile.tile_type}"]
            = tile.id

    .character_card style="left: 40rem"
      = form_with url: edit_tile_path do |f|
        .field.is-horizontal
          .field-label.is-horizontal
            = f.label :id, "Id", class: 'label'
          .field-body
            = f.number_field :id

        .field.is-horizontal
          .field-label.is-horizontal
            = f.label :tile_type, "Tipo", class: 'label'
          .field-body
            = f.text_field :tile_type, placeholder: "jungle_simple"
        .field.is-horizontal
          .field-label.is-normal
          .field-body
            = f.submit "Cambiar", class: "button is-success"
      - %w(jungle_simple jungle_undergrowth jungle_tree jungle_flowers jungle_water jungle_rocks castle_simple castle_wall castle_carpet castle_furniture castle_door castle_simple castle_wall castle_carpet castle_furniture castle_door cave_simple cave_wall cave_stone cave_bones cave_hole cave_water swamp_simple swamp_bush swamp_wood swamp_darkwood swamp_water desert_simple desert_sand desert_tree desert_wood desert_water snow_simple snow_ice snow_stone snow_tree snow_ground water_simple water_green water_stone water_tree water_deep city_simple city_house city_wood city_tree wall).each do |tile_type|
        .row_container
          p[class = "grid_button #{tile_type}"]
          p[style="margin-left: 1rem"] = tile_type
          hr

app/views/maps/index.html.slim
.container
  .title Mapas
  table.table.is-striped
    thead
      tr
        th Id
        th Nombre
        th Tipo
        th Visible? 
        th        
        th Editar      
    tbody
      - @maps.each do |map|
        tr
          td = map.id
          td = map.name
          td = map.map_type
          td = "#{map.is_current ? 'Sí' : 'No'}"
          - if map.is_current
            td = link_to "Quitar visibilidad", map_visibility_path(map.id), method: :delete
          - else
            td = link_to "Dar visibilidad", map_visibilities_path(id: map.id), method: :post
          td = link_to "Editar", edit_map_path(map)
      tr
        td = link_to "Crear mapa", new_map_path, class: "button is-black is-rounded is-small"

app/views/maps/new.html.slim
.container
  .title Simple creación de mapa
  = form_with model: @map, local: true do |f|
    .field.is-horizontal
      .field-label.is-horizontal
        = f.label :name, "Nombre", class: 'label'
      .field-body
        = f.text_field :name, placeholder: "jungle, castle, cave, swamp, desert, snow, water, city"
    .field.is-horizontal
      .field-label.is-horizontal
        = f.label :height, "Altura", class: 'label'
      .field-body
        = f.number_field :height, placeholder: "15"
    .field.is-horizontal
      .field-label.is-horizontal
        = f.label :width, "Ancho", class: 'label'
      .field-body
        = f.number_field :width, placeholder: "15"
    .field.is-horizontal
      .field-label.is-horizontal
        = f.label :map_type, "Tipo de mapa", class: 'label'
      .field-body
        = f.text_field :map_type, placeholder: "jungle, castle, cave, swamp, desert, snow, water, city"
    .field.is-horizontal
      .field-label.is-horizontal
        = f.label :background_image_link, "Imagen de fondo", class: 'label'
      .field-body
        = f.text_field :background_image_link, placeholder: ""
    .field.is-horizontal
      .field-label.is-normal
      .field-body
        = f.submit "Crear", class: "button is-success"