config/routes.rb
Rails.application.routes.draw do
  
  root to: 'maps#current'  #Principal page
  
  resources :movements, only: [:create] #Mueve una miniatura

  resources :characters, except: [:show]
  resources :character_views, only: [:create] #Es el js que se hace con js para la vista del mapa

  resources :maps, only: [:new, :edit, :create, :index] #Solo para el master
  resources :map_visibilities, only: [:create, :destroy] #Solo para el master

  resources :tiles, only: [:update] #Solo para el master
  post 'edit_tile', to: 'tiles#edit_tile'

  resources :attacks, only: [:create, :destroy]
  resources :armors, only: [:create, :destroy]
  resources :known_spells, only: [:create, :destroy]
  resources :prepared_spells, only: [:create, :destroy]


  get 'login', to: 'basic_pages#login'
  post 'login', to: 'basic_pages#register'  
  get 'logout', to: 'basic_pages#logout'
end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id           :bigint           not null, primary key
#  owner        :string
#  hp_max       :integer
#  hp_temp      :integer
#  current_hp   :integer
#  strength     :integer
#  dexterity    :integer
#  constitution :integer
#  wisdom       :integer
#  inteligence  :integer
#  charisma     :integer
#  name         :string
#  icon         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  is_current   :boolean
#  ordinate     :integer
#  abscissa     :integer
#

class Character < ApplicationRecord
  has_many :attacks
  has_many :armors
  has_many :known_spells
  has_many :prepared_spells, through: :known_spells
  
  scope :owner_is, ->(owner){where('characters.owner = (?)', owner)}
  scope :in_map, -> {where(is_current: true)}

  def self.broadcast_positions
    positions = Character.in_map.map do |ch|
      {abscissa: ch.abscissa, ordinate: ch.ordinate, icon: ch.icon}
    end
    BoardChannel.broadcast_to("board_channel", positions)
  end

  def calculate_ac
    armors.sum(:value)
  end

  def make_visible
    self.update(is_current: true, ordinate: 0, abscissa: 0)    
  end

  def kill
    self.update(is_current: false, ordinate: 0, abscissa: 0)    
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :check_for_master, only: [:delete, :update]

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    if @character.save
      redirect_to edit_character_path(@character)
    else
      render 'new'
    end
  end

  #Acá se adicionan ataques y pendejadas
  def edit
    @character = Character.owner_is(cookies[:user]).find(params[:id])
    @attack = @character.attacks.build
    @armor = @character.armors.build
    @spell = @character.known_spells.build
  end

  def update
    puts params
    #Acá el master elige quién es visible
  end

  def index        
    unless cookies[:user] == "Mmaster"
      @characters = Character.owner_is(cookies[:user])    
    else
      @characters = Character.all    
    end
  end

  def show
    if cookies[:user] == "Mmaster"
      @character = Character.find(params[:id])    
    else
      @character = Character.owner_is(cookies[:user]).find(params[:id])    
    end
  end

  def delete

  end

  private

  def character_params
    params.require(:character).permit(
      :hp_max,
      :strength,
      :dexterity,
      :constitution,
      :wisdom,
      :inteligence,
      :charisma,
      :name,
      :icon
      ).merge(owner: cookies[:user])
  end
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/views/characters/edit.html.slim
/Tengo acceso a @character, @attack (nuevo), @armor (nuevo)
.container
  .is-size-1 = "#{@character.name} #{@character.icon}"
  .columns
    .column.is-3
      .is-size-3.has-text-link Características
      table.table.is-bordered.is-striped
        tbody
          tr
            th Fue
            td = @character.strength
          tr  
            th Dex
            td = @character.dexterity
          tr  
            th Con
            td = @character.constitution
          tr  
            th Int
            td = @character.inteligence
          tr  
            th Sab
            td = @character.wisdom
          tr  
            th Cha
            td = @character.charisma
    .column.is-5
      .is-size-3.has-text-link Ataques
      table.table.is-narrow       
        thead
          tr
            th Arma
            th Atk bonus
            th Daño
        tbody
          - @character.attacks.each do |attack|
            tr
              th = attack.weapon
              td = attack.attack_bonus
              td = attack.damage_dice
          = form_with model: @attack, local: true do |f|
            tr
              td = text_field_tag :weapon, "",  placeholder: "Bofetada", size: "15"
              td = text_field_tag :attack_bonus, "",  placeholder: "+4", size: "4"
              td = text_field_tag :damage_dice, "", placeholder: "2d9 - 2", size: "10"
            tr
              td = hidden_field_tag :character_id, @character.id
              td 
              td = submit_tag "Agregar", class: "button is-dark is-rounded is-small"
    .column.is-4
      .is-size-3.has-text-link = "Armadura #{@character.calculate_ac}"
      table.table.is-narrow 
        thead
          tr
            th Armadura
            th Mod
        tbody
          - @character.armors.each do |armor|
            tr
              td = armor.name
              th = armor.value                
          = form_with model: @armor, local: true do |f|
            tr
              td = text_field_tag :name, "",  placeholder: "Escudo de hojas", size: "12"
              td = number_field :value, "",  placeholder: "13", size: "2"
            tr
              td = hidden_field_tag :character_id, @character.id
              td = submit_tag "Agregar", class: "button is-dark is-rounded is-small"
  .columns
    .column.is-12
      .is-size-3.has-text-link Hechizos conocidos
      table.table.is-narrow       
        thead
          tr
            th Nombre
            th Nivel
            th V S M F DF XP
            th Cast time
            th Rango
            th Duración
            th Salvación
            th R.C.
            th Descripción
            th Preparados
        tbody
          - @character.known_spells.order(:level).each do |spell|
            tr
              th = spell.name
              th = spell.level
              td = spell.components
              td = spell.casting_time
              td = spell.range
              td = spell.duration
              td = spell.saving_throw
              td = spell.spell_resistance ? "Sí" : "No"
              td = spell.description
              td
                = spell.prepared_spells.count
                = link_to "add", prepared_spells_path(known_spell_id: spell.id), class: "material-icons md-18", style: "font-size: 1rem; font-weight: bold;", method: :post


          = form_with model: @spell, local: true do |f|
            tr
              td = text_field_tag :name, "", placeholder: "Rayo abrazador", size: "6"
              td = number_field_tag :level, "",  placeholder: "0", size: "2"
              td
                = check_box_tag :verbal
                = check_box_tag :somatic
                = check_box_tag :material
                = check_box_tag :focus
                = check_box_tag :divine_focus
                = number_field_tag :xp, "",  placeholder: "0", size: "4"
              td = text_field_tag :casting_time, "", placeholder: "estándar", size: "4"
              td = text_field_tag :range, "", placeholder: "1'", size: "4"
              td = text_field_tag :duration, "", placeholder: "1 ronda", size: "4"
              td = text_field_tag :saving_throw, "", placeholder: "dex 1/2", size: "4"
              td = check_box_tag :spell_resistance
              td = text_area_tag :description, "", placeholder: "dex 1/2", size: "29"
            tr
              td = hidden_field_tag :character_id, @character.id
              td
              td
              td
              td
              td
              td
              td
              td = submit_tag "Agregar", class: "button is-dark is-rounded is-small"    
/level
/verbal
/somatic
/material
/focus
/divine_focus
/xp
/casting_time
/range
/duration
/saving_throw
/spell_resistance

app/views/characters/index.html.slim
/ Tengo acceso a @characters
.container
  .title Mis mostros!
  table.table.is-striped
    thead
      tr
        th id
        th Nombre
        th Ataques
        th Armadura
    tbody
      - @characters.each do |monster|
        tr
          td = monster.id
          td = link_to "#{monster.icon} #{monster.name}", edit_character_path(monster)
          td = monster.attacks.count
          td = monster.calculate_ac
      tr
        td = link_to "Quiero otro", new_character_path, class: "button is-black is-rounded is-small"

app/views/characters/new.html.slim
.container
  .title Hora de crear un nuevo personaje
  .subtitle Datos básicos
  = form_with model: @character, local: true do |f|
    .field.is-horizontal
      .field-label.is-horizontal
        = f.label :name, "Nombre", class: 'label'
      .field-body
        = f.text_field :name, placeholder: "Chtulu"
    .field.is-horizontal
      .field-label.is-horizontal
        = f.label :icon, "Miniatura", class: 'label'
      .field-body
        = f.text_field :icon, placeholder: "👽"
    .field.is-horizontal
      .field-label.is-normal
        = f.label :strength, "Fuerza", class: 'label'
      .field-body
        = f.number_field :strength, placeholder: 10
    .field.is-horizontal
      .field-label.is-normal
        = f.label :dexterity, "Destreza", class: 'label'
      .field-body
        = f.number_field :dexterity, placeholder: 10
    .field.is-horizontal
      .field-label.is-normal
        = f.label :constitution, "Constitución", class: 'label'
      .field-body
        = f.number_field :constitution, placeholder: 10
    .field.is-horizontal
      .field-label.is-normal
        = f.label :wisdom, "Sabiduría", class: 'label'
      .field-body
        = f.number_field :wisdom, placeholder: 10
    .field.is-horizontal
      .field-label.is-normal
        = f.label :inteligence, "Inteligencia", class: 'label'
      .field-body
        = f.number_field :inteligence, placeholder: 10
    .field.is-horizontal
      .field-label.is-normal
        = f.label :charisma, "Carisma", class: 'label'
      .field-body
        = f.number_field :charisma, placeholder: 10
    .field.is-horizontal
      .field-label.is-normal
      .field-body
        = f.submit "Crear", class: "button is-success"
    