config/routes.rb
Rails.application.routes.draw do
  
  root to: 'maps#current'  #Principal page
  
  resources :movements, only: [:create] #Mueve una miniatura

  resources :characters, except: [:show]
  resources :character_views, only: [:create] #Es el js que se hace con js para la vista del mapa

  resources :maps, only: [:new, :edit, :create, :index] #Solo para el master
  resources :map_visibilities, only: [:create, :destroy] #Solo para el master

  resources :tiles, only: [:update] #Solo para el master
  post 'edit_tile', to: 'tiles#edit_tile'

  resources :attacks, only: [:create, :destroy]
  resources :armors, only: [:create, :destroy]
  resources :known_spells, only: [:create, :destroy]
  resources :prepared_spells, only: [:create, :destroy]


  get 'login', to: 'basic_pages#login'
  post 'login', to: 'basic_pages#register'  
  get 'logout', to: 'basic_pages#logout'
end

app/controllers/basic_pages_controller.rb
class BasicPagesController < ApplicationController
  skip_before_action :check_for_user

  def login
  end

  def register
    cookies.permanent[:user] = params[:user]
    redirect_to root_path
  end

  def logout
    cookies.delete :user
    redirect_to root_path
  end
end

app/helpers/basic_pages_helper.rb
module BasicPagesHelper
end

app/views/basic_pages/home.html.slim
h3 Acá irá una barra de navegación, si nos gusta tal idea

.map_container
  img.is_background src="https://ddalsg.files.wordpress.com/2018/09/burning_city.jpg?w=750"  
  .grid_container
    - 15.times do |n|
      .row_container
        - 15.times do |n|
          button.grid_button      
    - n = 33.18
    p.miniature.medium style="left: 33.18rem" &nbsp;🏃  
    p.miniature.big.x1.y1 style="left: #{n}rem" &nbsp;🐺
    p.miniature.medium.x2.y2 &nbsp;🐺

    - ancho = 40
    .card style="left: #{ancho}rem"
      = radio_button_tag :personaje, "Lobo"      
      = label_tag :age_child, "🐺 Lobo"      
      = radio_button_tag :age, "Aramil"
      = label_tag :age_adult, "🏃 Aramil"
      p Fue 15(2) Dex 8(-1) Con 20(5) Int 14(2) Car 17(3) Sab 12(1)
      p HP max: 11, HP actual + temp: 5 + 4
      p AC: 12
      h3 Ataques
      ul
        li Espada corta: +3/1d6+1
        li Escupirle en la cara: -1/1d2-1
        li Hacerle muecas: +3/1d12+7
      h3 Hechizos conocidos
      = select(:asdf, :nivel, [['Nivel 0', 0], ['Nivel 1', 1], ['Nivel 2', 2]])
      ul 
        li Bola de fuego frío: 30' + 5'/nivel; CD 15; 2d4-1
          | tiempo de lanzamiento: 10 min; duración 1 min
        li Bola de fuego frío: 30' + 5'/nivel; 1d20 + INT; 2d4-1
          | tiempo de lanzamiento: 10 min; duración 1 min
        li Bola de fuego frío: 30' + 5'/nivel; CD 15; 2d4-1
          | tiempo de lanzamiento: 10 min; duración 1 min

app/views/basic_pages/login.html.slim
= form_with(url: login_path, method: :post, local: true) do
  = label_tag(:user, "Personaje") 
  = text_field_tag(:user) 
  = submit_tag("¡Vamos!") 