config/routes.rb
Rails.application.routes.draw do
  
  root to: 'maps#current'  #Principal page
  
  resources :movements, only: [:create] #Mueve una miniatura

  resources :characters, except: [:show]
  resources :character_views, only: [:create] #Es el js que se hace con js para la vista del mapa

  resources :maps, only: [:new, :edit, :create, :index] #Solo para el master
  resources :map_visibilities, only: [:create, :destroy] #Solo para el master

  resources :tiles, only: [:update] #Solo para el master
  post 'edit_tile', to: 'tiles#edit_tile'

  resources :attacks, only: [:create, :destroy]
  resources :armors, only: [:create, :destroy]
  resources :known_spells, only: [:create, :destroy]
  resources :prepared_spells, only: [:create, :destroy]


  get 'login', to: 'basic_pages#login'
  post 'login', to: 'basic_pages#register'  
  get 'logout', to: 'basic_pages#logout'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar is-black" role="navigation" aria-label="main navigation">  
  <div class="navbar-menu is-active">
    <div class="navbar-start">
      <%= link_to "Mapa actual", root_path, class: "navbar-item" %>
      <% if cookies[:user] %>
        <%= link_to "Cerrar sesión", logout_path, class: "navbar-item" %>
      <% end %>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Personajes
        </a>

        <div class="navbar-dropdown">
          <%= link_to "Mis personajes", characters_path, class: "navbar-item" %>
          <%= link_to "Nuevo", new_character_path, class: "navbar-item" %>          
      </div>
    </div>

    <div class="navbar-end">
      <% if cookies[:user] == "Mmaster" %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Mapas
          </a>
          <div class="navbar-dropdown">
            <%= link_to "Todos", maps_path, class: "navbar-item" %>
            <%= link_to "Nuevo", new_map_path, class: "navbar-item" %>          
        </div>
      <% end %>
      

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dungeon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">  
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>